version: "3.2"
services:

  chocolate:
    image: chocolateyfest/chocolate:latest
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.platform.os == windows
